/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppTodo {}
  interface AppTodoAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppTodo': Components.AppTodo;
  }

  interface StencilIntrinsicElements {
    'app-todo': Components.AppTodoAttributes;
  }


  interface HTMLAppTodoElement extends Components.AppTodo, HTMLStencilElement {}
  var HTMLAppTodoElement: {
    prototype: HTMLAppTodoElement;
    new (): HTMLAppTodoElement;
  };

  interface HTMLElementTagNameMap {
    'app-todo': HTMLAppTodoElement
  }

  interface ElementTagNameMap {
    'app-todo': HTMLAppTodoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
